version: "3"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    healthcheck:
      test: ["CMD", "mariadb", "-u${DB_USER}", "-p${DB_PASSWORD}", "--port=${DB_PORT}", "--host=${DB_HOST}"]
      interval: 2s
      timeout: 3s
      retries: 5
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./scripts/init.sh:/docker-entrypoint-initdb.b/init.sh
      - mariadata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - system-facing

volumes:
    mariadata:
      driver: local
networks:
  user-facing:
  system-facing:
