"""fixed user_id field in Post entity

Revision ID: 1a4a282ec606
Revises: 4ac92b3fe385
Create Date: 2024-03-18 16:06:52.757070

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "1a4a282ec606"
down_revision: Union[str, None] = "4ac92b3fe385"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("user_id", sa.Integer(), nullable=True))
    op.drop_constraint("post_ibfk_1", "post", type_="foreignkey")
    op.create_foreign_key(None, "post", "user", ["user_id"], ["id"])
    op.drop_column("post", "user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post",
        sa.Column(
            "user", mysql.INTEGER(display_width=11), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "post", type_="foreignkey")
    op.create_foreign_key("post_ibfk_1", "post", "service", ["user"], ["id"])
    op.drop_column("post", "user_id")
    # ### end Alembic commands ###
