"""design revision implemented 2

Revision ID: bd161bfda58a
Revises: ea14cca11a92
Create Date: 2024-03-18 03:45:34.282553

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd161bfda58a"
down_revision: Union[str, None] = "ea14cca11a92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "answer",
        sa.Column("answer_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "answer", sa.Column("recommend_service", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "question",
        sa.Column("question_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question", "question_text")
    op.drop_column("answer", "recommend_service")
    op.drop_column("answer", "answer_text")
    # ### end Alembic commands ###
