"""initial migration

Revision ID: e75e1a2374aa
Revises:
Create Date: 2024-03-12 02:15:48.664629

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "e75e1a2374aa"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event")
    op.drop_table("admin")
    op.drop_table("post")
    op.drop_table("service")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("service_name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("username", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("password", mysql.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "post",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "service_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("title", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("content", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"], name="post_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "admin",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("username", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("password", mysql.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "event",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "service_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("title", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("content", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("start_date", mysql.DATETIME(), nullable=False),
        sa.Column("end_date", mysql.DATETIME(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"], name="event_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
