"""design revision implemented

Revision ID: ea14cca11a92
Revises: a95fed07b5c8
Create Date: 2024-03-15 01:50:59.500347

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "ea14cca11a92"
down_revision: Union[str, None] = "a95fed07b5c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "SERVICE", "STUDENT", name="userrole"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "survey",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["service.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "question",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("survey_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["survey_id"],
            ["survey.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "answer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("admin")
    op.add_column("event", sa.Column("user_id", sa.Integer(), nullable=True))
    op.drop_constraint("event_ibfk_1", "event", type_="foreignkey")
    op.create_foreign_key(None, "event", "user", ["user_id"], ["id"])
    op.drop_column("event", "service_id")
    op.add_column("post", sa.Column("user", sa.Integer(), nullable=True))
    op.drop_constraint("post_ibfk_1", "post", type_="foreignkey")
    op.create_foreign_key(None, "post", "service", ["user"], ["id"])
    op.drop_column("post", "service_id")
    op.add_column("service", sa.Column("user_id", sa.Integer(), nullable=False))
    op.add_column(
        "service", sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "service",
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "service",
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "service",
        sa.Column("website_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_foreign_key(None, "service", "user", ["user_id"], ["id"])
    op.drop_column("service", "username")
    op.drop_column("service", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service", sa.Column("password", mysql.VARCHAR(length=255), nullable=False)
    )
    op.add_column(
        "service", sa.Column("username", mysql.VARCHAR(length=255), nullable=False)
    )
    op.drop_constraint(None, "service", type_="foreignkey")
    op.drop_column("service", "website_url")
    op.drop_column("service", "address")
    op.drop_column("service", "phone_number")
    op.drop_column("service", "email")
    op.drop_column("service", "user_id")
    op.add_column(
        "post",
        sa.Column(
            "service_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "post", type_="foreignkey")
    op.create_foreign_key("post_ibfk_1", "post", "service", ["service_id"], ["id"])
    op.drop_column("post", "user")
    op.add_column(
        "event",
        sa.Column(
            "service_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "event", type_="foreignkey")
    op.create_foreign_key("event_ibfk_1", "event", "service", ["service_id"], ["id"])
    op.drop_column("event", "user_id")
    op.create_table(
        "admin",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("username", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("password", mysql.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("answer")
    op.drop_table("question")
    op.drop_table("survey")
    op.drop_table("user")
    # ### end Alembic commands ###
