name: Deploy to Caprover Prod Cluster

on:
  release:
    types: [published]

env:
  BACKEND_IMG_NAME: ${{ github.repository }}/backend
  FRONTEND_IMG_NAME: ${{ github.repository }}/frontend


jobs:
  backend-CI:
    uses: campus-compass/campus-compass/.github/workflows/backend-updated.yml@main
    permissions:
      contents: read
      packages: write
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
  frontend-CI:
    uses: campus-compass/campus-compass/.github/workflows/frontend-updated.yml@main
    permissions:
      contents: read
      packages: write
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  deploy:
    needs: [frontend-CI, backend-CI]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend Image to CapRrover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.BACKEND_APP_NAME }}"
          token: "${{ secrets.BACKEND_APP_TOKEN }}"
          image: "${{ env.BACKEND_IMG_NAME }}"

      - name: Deploy Frontend Image to CapRrover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.FRONTEND_APP_NAME }}"
          token: "${{ secrets.FRONTEND_APP_TOKEN }}"
          image: "${{ env.FRONTEND_IMG_NAME }}"
